### ISSUE TITLE
Documenting Keyboard

### ISSUE THREAD

**Issue by leecher1337** [jwise/x2100-ec#11]
Do you plan to document the inner workings of the keyboard controller code too?
I have a L530 Notebook with the same EC and trying to get the keyboard mapping right with a 7-row keyboard.
As far as I understand, X210 has a 7-row keyboard, so part of the firmware could be maybe ported, but I don't understand the mechanisms so far

https://github.com/hamishcoleman/thinkpad-ec/issues/203

**Comment by exander77** [comment]
There was documentation from vladisslav for X210 of keyboard mappings, but the link is long dead.

**Comment by leecher1337** [comment]
Nevermind, I found it out for my firmware by reverse engineering and documented it here: 
https://github.com/leecher1337/thinkpad-Lx30-ec/blob/main/doc/keyboard.md
